### ISSUE TITLE
GitHub social media card

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#127]
Ideally, we need a GitHub social media card that includes the package title and logo. There may be packages available for making these or it may need to be manually done.

**Comment by Bisaloo** [comment]
On that topic, shouldn't the opengraph metadata use the logo rather than a plot?

https://github.com/epiforecasts/epinowcast/blob/603782bece7cea70d68287d4481fc0dc08a006b8/_pkgdown.yml#L12

**Comment by seabbs** [comment]
> On that topic, shouldn't the opengraph metadata use the logo rather than a plot?

Likely yes, this comes from before there was a logo I think. There may be a few other instances like this that weren't updated when the logo was added.

**Comment by seabbs** [comment]
Thanks, Hugo. Nice to see some cool use of `magick`. So I was really thinking of something with a bit more detail (i.e at least the package title) but a little more custom than the GitHub default. 

So the default is actually much better than I had realised and looks like this: 

![Screenshot 2022-08-21 at 14 34 35](https://user-images.githubusercontent.com/20317649/185793628-235e013a-bc1d-489f-9caa-07ca186bf716.png)

and the custom card currently looks like this:

![Screenshot 2022-08-21 at 14 34 54](https://user-images.githubusercontent.com/20317649/185793635-1e180a89-ac7f-47b8-98e1-f634ffc70cc4.png)

So I think in many ways perhaps the default is doing what we need? In an ideal world, no branding, it would have the package vs the org logo, and we would also have a card we could use elsewhere (i.e for `pkgdown` which currently has some issues)? I haven't seen any of these in the wild though so perhaps the consensus is the GitHub default is good enough? 

![Screenshot 2022-08-21 at 14 41 52](https://user-images.githubusercontent.com/20317649/185793757-36f97527-7075-405f-b727-9639ed9610d3.png)

For now, I have reverted to the default social media card.

**Comment by Bisaloo** [comment]
I could easily add the repo name with magick to have card with the pkg logo but I think we would then lose the repo "social info" (number of issues, number of stars, etc.). Unless we regenerate the card every day / week but it seems overkill.

**Comment by seabbs** [comment]
After mulling this over and based on our chat it seems like sticking with the default is the sensible way to go.
