### ISSUE TITLE
Document parametric delay distribution types

### ISSUE THREAD

**Issue by adrian-lison** [epinowcast/epinowcast#129]
We should better document the different parametric delay distributions available in epinowcast, i.e. add links to the parameterization (to the stan documentation, wikipedia, or where?) and potentially add a part in the model vignette where the different distributions and their parameterizations are explained. This will become especially important if users want to tweak priors for the parameters.

**Comment by adrian-lison** [comment]
This should be mainly covered but I can check.

**Comment by seabbs** [comment]
How are we feeling about this? I think it is mainly covered?

**Comment by seabbs** [comment]
(I just unassigned you @adrian-lison in case anyone else is looking for something to do but obviously please do do this if you get the chance!)

**Comment by seabbs** [comment]
Any luck on this @FelixGuenther?

**Comment by FelixGuenther** [comment]
Yes, I had a look and figured out how it’s done. Need some time for writing the documentation though. Would Monday evening be okay? Maybe on Monday we can also have a quick chat about where best to do the documentation?

**Comment by seabbs** [comment]
Yup sounds amazing. Monday morning is best for me or 5 UK time?

**Comment by seabbs** [comment]
How is this going @FelixGuenther?

**Comment by FelixGuenther** [comment]
I just pushed some additions to the model vignette to a new branch in commit 1def915 . Can you check whether you agree with what I wrote there?

**Comment by adrian-lison** [comment]
Thanks a lot @FelixGuenther! I had a look and made some minor changes, will do a bit more fine-tuning tomorrow.

One thing I was wondering if we should really explain how exactly the discretisation is computed in this vignette, or whether we can build the necessary understanding/intuitions by just providing the formulas of the resulting discrete distributions. I am talking about the differencing stuff etc.

**Comment by seabbs** [comment]
> One thing I was wondering if we should really explain how exactly the discretisation is computed in this vignette, or whether we can build the necessary understanding/intuitions by just providing the formulas of the resulting discrete distributions. I am talking about the differencing stuff etc.

An additional motivator for this is that I think we are not handling discretisation entirely correctly in that we only account for secondary event censoring. We are not alone in that issue but if trying to convert to/from continuous I think it leads to 1/2 day of bias. Still working/thinking about this. In the first instance though being really explicit about what we are doing seems like it might be a good idea?

**Comment by adrian-lison** [comment]
@FelixGuenther @seabbs I did another bunch of refactoring on the whole delay distribution part, mostly restructuring the text to fit more naturally into one section, and making the overall notation more accurate. I made a PR for this now, see #265 , to go through the remaining details together.

**Comment by seabbs** [comment]
Its looking good to me. Added some comments to the PR.
