### ISSUE TITLE
Add data format converters

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#144]
At the moment we require our input data as a cumulative count. This makes sense for many classic nowcasting problems but makes less sense for some forms of data and in particular linelist data.

We should consider adding the following new functions. 

- [x] `enw_linelist_to_incidence()` aggregate a individual linelist to aggregated counts
- [x] `enw_incidence_to_cumulative()` aggregate incidence count data to cumulative.
- [x] `enw_cumulative_to_incidence()`
- [x] `enw_incidence_to_linelist()`

These functions are also likely useful for exploring data and potentially simulation. We want them to support `by` arguments as discussed in #143.

There is a version of `enw_incidence_to_cumulative()` as part of #138 which can be pulled out and improved. 

`enw_new_reports()` is effectively `enw_cumulative_to_incidence()`. It could be renamed and depreciated using `lifecycle`.

**Comment by seabbs** [comment]
@sbfnk this is likely good functionality for a spin-off/another package. Parts of this are available in, for example, `incidence2` but I don't think on a way that is sufficiently generic/flexible for our use case.

**Comment by seabbs** [comment]
I made a start on `enw_incidence_to_cumulative()` and renamed `enw_new_reports()` to `enw_cumulative_to_incidence()` as part of trying to debug simulation code for the missing data model.

**Comment by seabbs** [comment]
I've pulled out work on `enw_incidence_to_cumulative()` and `enw_cumulative_to_incidence()` in #157.

**Comment by jhellewell14** [comment]
One thing to choose I think is what exactly you want out. At the moment `cumul_to_inc` adds a column `new_confirm` and the column `confirm` continues to exist so that data.table now has both cumul and inc. With linelist conversion what you get out looks nothing like the original linelist. 

So maybe it would be better to think of it as three functions:
1) `enw_add_inc_to_cumul` (adds `new_confirm` and % reported cumulatively if not present to incidence data)
2) `enw_add_cumul_to_inc` (adds `confirm` and % reported cumulatively to cumulative data)
3) `enw_linelist_to_dt` (produces dt with `confirm`, `new_confirm`, and % reported from linelist data)

**Comment by jhellewell14** [comment]
I've put a start at the linelist conversion function here: https://github.com/jhellewell14/epinowcast/commit/65463ddb0541a1f2fe676224b3daeb125b01e086 

I have also included a fake linelist dataset that might be relevant for part of https://github.com/epiforecasts/epinowcast/issues/94

**Comment by seabbs** [comment]
Yes, agree on multiple functions. Potentially the linelist only needs to be converted to either incidence or cumulative (likely incidence as easier) and then the user uses that to calc cumulative with another function call? I like the idea of making sure the output is standardised. Currently the thinking is the cumulative data is this standardised dataset but can see the argument for why each of these should produce the same dataset as well.

**Comment by seabbs** [comment]
I added a few comments - looks good so far. I am not 💯  that each function should result in the same output vs chaining them but I am nearly convinced 😆. Might be the case that others have strong opinions about this but does seem like your suggestion would make it as easy as possible for the user.

**Comment by seabbs** [comment]
Thinking some more about this we could have less functionality in `enw_preprocess_data` if we took this approach (as we wouldn't need to calculate new confirmations or add delay metadata. This could make @FelixGuenther life easier in the long term but more painful in the short term (as would need to refactor his visualisation work). 

To be clear this would: 

- Add a new constructor function that a user would always need to use regardless of data format (instead of as currently forcing conversion to cumulative and going from there). This is because they are defining a standard data format with all the new converter functions. 
- Make the expected input to `enw_preprocess_data()` be a standardised object itself that came with delays, new confirmations, confirmations etc. 
- `enw_preprocess_data()` would then handle max delay settings, adding a grouping variable, and the various modelling data we need. 
- Potentially this would make it less clear what should be used for visualisation but in many circumstances, it seems like vis would be useful on both the input object and the output from `enw_preprocess_data` rather than on the `enw_preprocess_data()` object itself. 

This could scale up to a fairly large change in how preprocessing feels to the user and is organised so keen to hear what others think. Particularly a clear list of expected upsides/downsides.

**Comment by jhellewell14** [comment]
My view would be to cater as much as possible to people in PH institutions that may not have programming backgrounds who just need to get their linelists into R somehow and chuck them into epinowcast with as little data wrangling or decision making (except for where you can present these decisions as "if your data is like X, choose Y" ) as possible. 

I've only just started trying to contribute so I leave to you where you best think everything should go but I am happy to help do it.

**Comment by seabbs** [comment]
See #158 for some initial work on linelist conversion from @jhellewell14. From chatting he/we aren't likely to be able to work more on this issue for a few weeks so if anyone else wants to pick it up that would be great.

**Comment by seabbs** [comment]
Any chance you've got some capacity to push forward on this @jhellewell14? It would be nice to integrate the stuff already done here.

**Comment by seabbs** [comment]
Closed in #247
