### ISSUE TITLE
Black bar in html documentation website

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#159]
In both the release (https://epiforecasts.io/epinowcast/) and development (https://epiforecasts.io/epinowcast/dev) web documentation, I currently see a black bar. This looks like an issue with the template (`preferably`) we are using and could be linked to an interaction with `pkgdown` or other package features. 

The sensible first debugging step would be to check the documentation (using `pkgdown::build_site()`) with different versions of the template and `pkgdown`  (i.e from GitHub etc.). If the issue is with our configuration then none of this will help. The next step would be explore the commits prior to our recent `main` release up to the last release (and potentially starting there as that is the last point we know we had fully working docs). Hopefully this should highlight if we have introduced a configuration issue.

![Screenshot 2022-08-16 at 10 00 28](https://user-images.githubusercontent.com/20317649/184841473-df050bea-39e8-4719-a03c-b943a2d70bc5.png)

**Comment by Bisaloo** [comment]
Everything looks normal with the light theme on my end. However, if I switch to the dark theme, I get a white bar where you get your black bar :exploding_head:

**Comment by seabbs** [comment]
It looks like this may have been fixed in the latest GitHub release of `preferably`

**Comment by seabbs** [comment]
Sounds like some kind of odd caching effect?

**Comment by Bisaloo** [comment]
I think the js code fails to change [the `prefers-color-scheme` setting](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). Even when changing, I'm still stuck on the old one. On the other, if I manually change this setting, everything looks fine, no more black/white bar.

**Comment by seabbs** [comment]
In https://github.com/epiforecasts/epinowcast/commit/5ea76ff6c4368d2a8f1865ef42dbc767841c9b84 as suggested in https://github.com/amirmasoudabdol/preferably/pull/13 I've switched to automatic mode for dark/light themes. Personally, I find it useful to be able to change this so leaving this issue open until we have a more complete fix.

**Comment by seabbs** [comment]
This seems like an issue elsewhere so closing here.
