### ISSUE TITLE
Separate latent reporting delays from latent reporting scaling

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#179]
In #152 a latent reporting process was implemented that supported both delays in reporting and partial ascertainment by allowing the specification of a PMF that does not sum to 1. As @adrian-lison notes it may make more sense to separate this functionality into two arguments which could be called `latent_reporting_fraction` and `latent_reporting_delay`. Not that any changes along these lines need to be made with #177 in mind and this will substantially complicate both the front and back-end implementation.

**Comment by seabbs** [comment]
In #183 I've thought about it some more and based on needing time-varying reporting delays (i.e #177) and potentially group-specific ones it feels like keeping this as a linked option, for now, maybe simpler. If we do split out then we will need to manage the various permutations of both arguments and then combine them. 

Once we have better control of priors then manipulating the `observation` formula becomes a better option (though perhaps this also becomes complex when/if moving to a hazard model for this. 

Given this going to propose this issue gets closed out. What do you think @adrian-lison?

**Comment by adrian-lison** [comment]
Yes, I agee, with #183 in place now it would rather be a pain to separate the two, and not improve readibility. So let's close this.
