### ISSUE TITLE
Implement and evaluate sparse non-zero matrix multiplications

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#184]
In the current package, we use design matrices that are sparse in the sense of only using unique rows and then linking to the non-sparse design matrix. This is useful where we are doing lots of computation by row for example when calculating parametric delays but is otherwise of minimal utility. 

Sparse matrices usually refer to matrices that drop zeros and this implementation is available in `stan` (https://mc-stan.org/docs/functions-reference/sparse-matrix-arithmetic.html). This type of sparse matrix generally only make sense when zeros make up more than 90% of a matrix.

This might be useful when we have users specifying large design matrices that have many zeros. An obvious case in point would be large random effects. However, as these parts of the model typically don't take the majority of the runtime this may only be a minor optimisation if it is one at all.

An example of a sparse matrix implementation can be seen here for the latent reporting distribution:

https://github.com/epinowcast/epinowcast/commit/7afacea8fe55442eb3538f358254509730da6d87

**Comment by adrian-lison** [comment]
Agree, I don't expect much reduction in runtime from this and the use case is rather specific, so I propose to keep this as low priority.

**Comment by seabbs** [comment]
I'm thinking we just don't need this and so should close out? Happy to reopen if we think its something we should do but just not now?
