### ISSUE TITLE
Allow for max_delay to be more flexible

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#204]
Currently, we force the user to set`max_delay` and if it is more than the max available in the data then the downstream model fitting fails. This is not a good user experience and is poorly explained. 

Two potential features could be added to alleviate this: 

1. Default to the maximum delay in the data and message the user that this has happened
2. Add support in the stan model for delays that are longer than the data. 

2. Is somewhat dangerous as depending on model settings could be very uninformed. However, we currently give a warning and fleshing this out might be enough?

This issue is related to #122.

**Comment by seabbs** [comment]
Which of these options makes sense to you @adrian-lison?

**Comment by adrian-lison** [comment]
I think I would prefer option 1, combined with a warning.

Main reason is that in principle we want users to set large maximum delays if resources allow, as this will be more accurate. Now, when nowcasting on a moving data window such as in real-time settings, the maximum delay observed in the data could jump around a lot from week to week. I believe this can cause a lot of trouble especially with non-parametric delay distributions. This would then force the user to always adapt the maximum delay to the observed delay (which option 1 would do automatically), or incentivize the user to set a shorter delay that always fits, which is not what we want really.

I don't think that defaulting to the maximum observed delay would be very different to supporting delays beyond the data in terms of inference results in typical settings. My only concern would be that but it could make postprocessing of estimated delay distributions etc. a bit less consistent for the user. Maybe we could account for this by extending postprocessed results such as delay distributions to the maximum delay that was set by the user (e.g. just adding NAs or zeros for all the delays that were not observable in the data?)

@seabbs I can give this a go if you like.

**Comment by adrian-lison** [comment]
@seabbs But do you mean that the extension with zeros to the specified maximum delay is something that should be done in the parts handled by #144, or can we use it as default here as well? Because this would be another option, whenever the specified `max_delay` is larger than the observed one, extend and warn.

**Comment by seabbs** [comment]
I think we should reduce and warn but make it clear in the docs what can be done if users want to expand (i.e use `enw_complete_dates`.

**Comment by seabbs** [comment]
I think we should consider bumping this to `0.3.0` as the rest of the release is nearly in place and I think there is still a bit to do on this?

**Comment by seabbs** [comment]
So I think we might need more time on this? For this reason going to bump it into the `0.3.0` release vs it being part of `0.2.1` as originally planned.
