### ISSUE TITLE
Depreciate enw_dates_to_factors

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#206]
We currently export a function `enw_dates_as_factors` that converts dates to factors and drops all other variables. As far as I can tell it is unused in our current code base and also seems unlikely to be needed by the user? 

Given this, I think we can make the case for soft depreciating it to reduce technical debt. 
Use case: 

```r
data <- data.frame(date = as.Date("2019-01-01") + 0:2, x = 1:3)
enw_dates_to_factors(data)
```

**Comment by adrian-lison** [comment]
You probably mean `enw_dates_to_factors`, right?

This was before my time, but apparently you only it used for the following:
```
enw_day_model <- function(metaobs, rw = FALSE) {

  # turn dates into factors
  metaobs <- enw_dates_to_factors(metaobs)

  # build effects design matrix (with  no contrasts)
  fixed <- enw_design(~date, metaobs, no_contrasts = TRUE)

 ...
}
```

I can't think of a need for this atm.
