### ISSUE TITLE
Required object types for users

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#211]
There's a general engineering principle to minimize constraints on external interfaces, as well as minimizing *promised* capabilities (at least until there's an identified demand for a capability).

Should pursue that for epinowcast generally. Known TODOs:
 - [ ] `data.frame` vs `data.table` inputs + documentation
 - [ ] `data.table` outputs + documentation
 - [x] CONTRIBUTING guidelines to reflect this principle
 - [ ] review for other interface items potentially violating this principle

In general, we should only require `data.frame` inputs (n.b. this of course includes `data.table` inputs). In many cases, we could allow *more* inputs (because `as.data.table` will handle them), but that would lock us into that more complicated contract.

However, because the typical yields are `data.table`s and they behave slightly (but importantly) differently from `data.frame`s (and we don't want to recast everything to `data.frame`), we need to tell that to the users.

**Comment by pearsonca** [comment]
i think it's fine to return `data.table`: it "is a" `data.frame` with the narrow exception of pass-by-reference to functions, so people can toss into their "tidy" pipelines with aplomb.

the key is just to consistently tell people that's what they're getting, and probably have somewhere prominent a warning label / reminder (the README, package docs, vignette - but probably not on every single return doc).

**Comment by seabbs** [comment]
I'm not sure I have the mental fortitude to deal with this issue in this release... Do we think its critical we get this standardised now or can we push?

**Comment by pearsonca** [comment]
I think just the style guide => then gradual enforcement.

**Comment by seabbs** [comment]
I have split out tasks into their own issues in more addressable formats see #263 and #262. I have also addressed the syle guide in #264 which will close this issue when merged (in favour of #263 and #262).
