### ISSUE TITLE
DRY out manual specification of some match.arg'd items

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#212]
Some uses of `match.arg`  hard code the choices more than once. This pattern could potentially lead to hard to debug errors and should be updated.

https://github.com/epinowcast/epinowcast/blob/c1d9bee83bf9c60d5834a485eabf886dfc2087ba/R/preprocess.R#L14

Look at `match.arg` at an R prompt - will show you the function body (though agree the reflection code is a ...thing to grok). Agree can be carved as own small TODO (good-first-issue style).

_Originally posted by @pearsonca in https://github.com/epinowcast/epinowcast/pull/208#discussion_r1148571625_

**Comment by seabbs** [comment]
@pearsonca or @pratikunterwegs can I tempt either of you to take this on 😄

**Comment by seabbs** [comment]
If no one can take this on I may move it to a later release.
