### ISSUE TITLE
enw_add_pooling_effect drop string argument

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#213]
https://github.com/epinowcast/epinowcast/blob/c1d9bee83bf9c60d5834a485eabf886dfc2087ba/R/model-design-tools.R#L154

> what do you think about using `...` args here? basically: drop `string` arg, make `...` be passed to `finder_fn`? downside is that your default finder_fn isn't guaranteed to be passed its required args, but that kinda could already happen?

> `...` generally should be used with caution, but this seems like the natural case for them?

_Originally posted by @pearsonca in https://github.com/epinowcast/epinowcast/pull/208#discussion_r1148569265_

**Comment by pearsonca** [comment]
any particular test cases we want here? clearly, the `startsWith` option - anything else people use somewhat commonly? I don't think this needs to be extensive, but should do a few examples.

Also a bit wary of how elaborate we should be about introspection here - feel comfortable labelling the `...` as a caveat emptor item, and not trying to, say, check that they've specified / correctly spelled all required arguments to their custom function. Probably should be willing to check that it's non-empty, however.

**Comment by seabbs** [comment]
>  feel comfortable labelling the ... as a caveat emptor item, and not trying to, say, check that they've specified / correctly spelled all required arguments to their custom function. Probably should be willing to check that it's non-empty, 

agree on this. 

The only current use cases we have are `startsWith` and here https://github.com/epinowcast/epinowcast/blob/c1d9bee83bf9c60d5834a485eabf886dfc2087ba/R/formula-tools.R#L348. 

This function would see more use for those manually specifying random effects but with the new formula interface the need to do that has decreased a lot and so this should be fairly rare and potentially it could be moved to internal only.

**Comment by pearsonca** [comment]
If you think the use cases are that limited, I'd recommend making it internal. *If* there's user demand someday, can always re export it, but until then its just one more thing to heavily maintain / explain / comprehend.

**Comment by seabbs** [comment]
"Current" use cases. If you want to specify something fancy and custom that the formula interface doesn't support you need it so, especially for research it does have a user-facing role. As we want to encourage more contributions it seems like surfacing, documenting etc. this functionality makes sense despite the additional maintenance burden.

**Comment by seabbs** [comment]
I think we should leave it exported for now and gauge usage longer term. Keen to see the strings arg dropped.
