### ISSUE TITLE
Revisit lintr usage

### ISSUE THREAD

**Issue by Bisaloo** [epinowcast/epinowcast#218]
Hi,

I would like to suggest streamlining and tightening automated checks performed by lintr in this package:

- The current workflow will lint all files, which results in annoying annotations on files you didn't touch and don't intend to touch in your PR. To remedy this, the lintr team has released a [`lint-changed-files.yaml` workflow](https://github.com/r-lib/actions/blob/7434f9e8cb77ffadb7bd5227f5393307fd516f77/examples/lint-changed-files.yaml), which will extract modified files and run lintr only on these files.
- You only get a tiny fraction of lintr's power by using only the default linters. lintr has [many](https://lintr.r-lib.org/reference/best_practices_linters.html), [many](https://lintr.r-lib.org/reference/efficiency_linters.html) more linters that are turned off by default and that can identify potential bugs or inefficient code. Default linters are not based on stability or utility but only on whether they encode the tidyverse style or not. An immediate consequence of this is that only style annotations will be provided and you will miss on all the more advanced static analysis.

 If you believe a change here could be helpful, I can submit a PR to:

- Switch to the `lint-changed-files.yaml` workflow
- Try to turn on all linters
- Fix lints in the current codebase and selectively turn off linters that are identified as incompatible with some of your design choice / coding style.

**Comment by seabbs** [comment]
This sounds very useful @Bisaloo and I would be very keen to see these changes made. We are in the run up to a new minor release (`0.2.1`) so having this in place ahead of that could help us catch up issues we have not been scanning for up to now with our listing.

**Comment by seabbs** [comment]
Resolved in #220 by @Bisaloo
