### ISSUE TITLE
Improving the package contributing guide

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#234]
Our current contributing guide (`CONTRIBUTING.md`) offers some guidance but may be hard to new users to pass and may not give sufficient guidance as to the particular style we have adopted for various areas of our code base. It may also be hard from some users to find in the first place.

In terms of code style I would personally like to stick as closely to default `tidyverse` styles as possible as this makes it easy for new users and allows us to avoid having to maintain extensive custom documentation. 

There are a few areas where we may need more guidance especially when it comes our use of inputing checking (see #233), and `data.table`.

Some comments from contributors (see [here](https://github.com/epinowcast/epinowcast/pull/229) for the original):

## From @pearsonca 

Have y'all stood up style guidelines or some such? I think the practical solution is roughly:

- do this PR now (agree, generally better + doesn't make move to stopifnot harder)
- have those style guidelines in place
- have a issue(s) => PR(s) exclusively focused on implementing guidance item(s), including this one

## From @Bisaloo 

Maintaining a thorough style guide is so much work that I usually try to stick with existing ones, even if I disagree with some of their choices (as long as we still agree on most points obviously).

## From @pearsonca 

> Maintaining a thorough style guide is so much work that I usually try to stick with existing ones, even if I disagree with some of their choices (as long as we still agree on most points obviously).

Doesn't have to be complete (e.g. "the specified lintr config passes" covers a lot), and this is more of a "style" guide anyway. I think it's roughly at the moment:

- generally, name exported functions with enw_..., and don't do that for internal functions
- do check arguments on externally facing functions, don't on internal ones
- require data.frame only for inputs, indicate data.table for outputs
- (as of this discussion) check as many arguments at the outset of enw_ with stopifnot(...) block
Others?

I do think the contributing guidelines currently are too focused on "process" - that's useful, but it's distinctly worthwhile to establish what are the "vocabulary" or "idioms" for enw. That's has some elements of "style" guidelines, but is generally a bit more meta (i.e. human-enforceable only) than concrete (i.e. static analysis works fine).

**Comment by pearsonca** [comment]
Item that came up during `coerce_dt` PR:
 - use of the `..._add_...` in method names suggests side effects. Possible to explicitly embrace that?

**Comment by seabbs** [comment]
This appears to be mostly covered by #264 and so could be closed by it.
