### ISSUE TITLE
Replace use of `data.table::setDT()` with use of `coerce_dt()`

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#242]
There are two places (outside of the proposed `coerce_dt` that use `setDT`: `enw_add_pooling_effect` and `enw_nowcast_samples`.

I *think* `enw_add_pooling_effect` should just become `coerce_dt` (and have a pass-through copy argument). Less clear on the second case.

**Comment by seabbs** [comment]
> enw_add_pooling_effect

Yes it can. 

> enw_nowcast_samples

It is fine as is but can go to `coerce_dt` to make things consistent. It doesn't need a pass-through copy.

**Comment by seabbs** [comment]
Done in #239
