### ISSUE TITLE
`enw_formula_as_data_list()`s implementation could be improved to better align with DRY principles

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#245]
`enw_formula_as_data_list` is a bit convoluted and breaks the DRY (don't repeat yourself) principle:

https://github.com/epinowcast/epinowcast/blob/c1d9bee83bf9c60d5834a485eabf886dfc2087ba/R/model-tools.R#L32-L71

Seems would be clearer as roughly or similar:

```r
# ...initial checking stuff ...
data <- list()
data[c("fintercept", "the other pertinent variables")] <- 0
data[c("fdesign", "these other pertinent variables") <- list(numeric())
if (!missing(formula)) {
  data$fdesign <- formula$fixed$design
   # ... etc
}
names(data) <- sprintf("%s_%s", prefix, names(data))
return(data)
```

Updating this would make the code easier to maintain and expand in the future.

**Comment by seabbs** [comment]
Thanks for this @pearsonca

Small point but when you make this kind of issue can you link to the original code and ideally provide a summary of what the current issue is vs the suggested change (above is fine for me for example but hard to access for many contributors).

I agree the current implementation can be shorten and this looks like a workable way of doing it.

**Comment by seabbs** [comment]
Note that @Lnrivas has a draft PR seeking to address this issue here #249. Potentially help still needed supporting this if interested.
