### ISSUE TITLE
README equation rendering

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#271]
The rendered README equation text/background doesn't inherit from user settings (i.e., doesn't abide by light/dark mode).

Screenshot of current equation rendering:

![Screenshot from 2023-05-03 09-19-22](https://user-images.githubusercontent.com/1828039/235866720-6931c296-43db-4b8c-8272-a5ca2f72ee50.png)

**Comment by seabbs** [comment]
>  the citation bit should indicate the command to generation that content (citation("epinowcast")) and make that content more copy-paste friendly (no #> )

This is as output by `citation()` but happy to hear how to improve visibility. 

>  the equation rendering text/background doesn't inherit from user settings

Yes, this is annoying. No idea how to resolve it.

**Comment by seabbs** [comment]
(this might be better as two issues IMO)

**Comment by pearsonca** [comment]
Re citation - just point out that it's available via citation (not currently mentioned - easy fix) + change the formatting so that when one copies the code block, it doesn't come along w/ the prompts - that's probably a correctable artifact via some chunk option in the underlying `.Rmd`

For this sort of laundry list (succinctly describe-able, if not necessarily solveable in the same manner), I generally prefer an issue w/ tick boxes, rather than multiple issues linked together by a project. I'd generally see it as something solved by a single PR, with approximately one commit per tick box. Whereas the multi-issue + project approach would be solved by multiple PRs.

Do you see this one as being solved by multiple PRs?

**Comment by seabbs** [comment]
> Do you see this one as being solved by multiple PRs?

Yes

> For this sort of laundry list (succinctly describe-able, if not necessarily solveable in the same manner), I generally prefer an issue w/ tick boxes, rather than multiple issues linked together by a project. I'd generally see it as something solved by a single PR, with approximately one commit per tick box. Whereas the multi-issue + project approach would be solved by multiple PRs

Fair enough. I think we want to aim for one idea per issue vs grouping issues in meta-issues if we can. Given many contributors don't have a lot of time this makes it easier for people to pick things up and solve them. In this case a PR could target both of these at once or it could not.

**Comment by pearsonca** [comment]
More fleshing out process considerations: I'm also thinking in terms of the code-administrative bits (e.g. updating NEWS, dev version counter) -  if this were broken in mini issues, I'd be inclined to skip those steps, and only bother with that when the whole "issue" was resolved.

To me, that leans in the direction of a single issue, but I read you re wanting to enable shorter-duration contribution efforts.

**Comment by seabbs** [comment]
Agree there is a trade off but I think we probably want to aim for maximum modularity

**Comment by pearsonca** [comment]
don't worry about splitting - have done so.

**Comment by seabbs** [comment]
Dropped equations that were being rendered incorrectly in 6e7242317580c3d786b959bd865f89f80b57b0a0.
