### ISSUE TITLE
Improve documentation of discrete distributions

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#278]
From @sbfnk

Docs could be improved by: 

- escaping functions to improve readibility
- right-closing discretised bins

**Comment by sbfnk** [comment]
Thanks, and sorry for assuming linking to an issue didn't apply to minor PRs!

**Comment by seabbs** [comment]
No worries - just being a bit pedantic (and I have been loving the clean auto-releases this gives).

**Comment by seabbs** [comment]
Super clean: https://capture.dropbox.com/eRHJgFHo63ImdBlN
