### ISSUE TITLE
Improve documentation for enw_preprocess_data

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#279]
From @sbfnk 

- there is a typo for reference date in the function documentation
- The documentation fornmax_delay is hard to pass as it stands 
- max_delay is missing inputs checks, in particular for the minimum value that can be passed (which is 1 i.e. zero delay).

**Comment by sbfnk** [comment]
Thanks, and sorry for assuming linking to an issue didn't apply to minor PRs!

**Comment by seabbs** [comment]
As in #278 just me being a bit pedantic.
