### ISSUE TITLE
Getting help with stan vignette

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#289]
For model fitting we rely on stan via `cmdstan`. At the moment we don't provide any information to users about how to debug their models or where to look. I think it would be really useful to have a general vignette signposting resources, giving simple answers to common problems with the package (like the fact they will very often need to specify a higher adapt delta and why), and potentially  signposting where in the code to make changes in the model.

**Comment by seabbs** [comment]
@medewitt being cheeky and wondering if you would like to take this on (and actually if you even think its a good idea).

**Comment by medewitt** [comment]
Sure, go ahead and tag me and I'll put together a draft. Might have to reign me in as I will want to put in the gif of model exploration in the posterior geometry from one of I think McElreaths' presentations.

**Comment by seabbs** [comment]
Amazing!

I mean why would I want to constrain that desire! 

> And I do think it is a good idea to have resources available where users are mostly likely to look first

👍🏻  - I think the key is being helpful enough for those users whilst also making it clear they should check out the more detailed help elsewhere. We don't want to become their one stop shop.

**Comment by medewitt** [comment]
Note to self: working on this here: https://github.com/medewitt/epinowcast/tree/stan-resources

**Comment by seabbs** [comment]
How is this going @medewitt? Even if we just have a rough skeleton in place that would be great as we can improve on it iteratively!

**Comment by medewitt** [comment]
Slowly! I'll get cracking--I have a bit of an outline that I'll get to a shareable place.

**Comment by seabbs** [comment]
Any chance I can badger this into being in time for the proposed `0.2.3` release (#361)? Any kind of rough outline would be great.

**Comment by medewitt** [comment]
🙈  Yep...will crank through it this weekend.

**Comment by seabbs** [comment]
Urggh the pain of rebasing! I can also give you direct access to this repo if you don't already have it?

**Comment by medewitt** [comment]
@seabbs 🙏 that will make life so much easier!

**Comment by seabbs** [comment]
You should have got an invitation with write access? I'm not sure we have a process for write access anywhere but I would guess we should do it based on current scale for moving to contributor, write access, author?

**Comment by medewitt** [comment]
All the action is now on the stan-help branch

**Comment by seabbs** [comment]
Do you want any eyes on this early? I imagine there are a few people like @adrian-lison and @zsusswein who might have thoughts on what to tell people about stan.

**Comment by zsusswein** [comment]
I'd be happy to take a look! I'm busy with Thanksgiving stuff the next few days, but I have a long train ride on Monday I can spend on this.

**Comment by medewitt** [comment]
The more eyes, the better. I'll try to be better about comiting frequently 😄
