### ISSUE TITLE
Stop updating the dev version?

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#299]
We currently require PRs to increment the dev version. 

This is nice as it clearly shows changes over time but can cause require merge conflicts and maybe an annoying hassle for developers. We could consider stopping this practice (with a dev version only being needed when making a PR into a release version). 

If we want to make this change we would need to:

- [x] update the contributing guide to not mention updating the dev version.
- [x] update the PR message.
- [ ] Updating the release guide (do we have one/is it in the contributing guide) to include immediately making a dev version for the next release and/or the contributing guide if placing this responsibility on the first PR merged post a release (this feels a little dangerous).

**Comment by Bisaloo** [comment]
> Updating the release guide (do we have one/is it in the contributing guide) to include immediately making a dev version for the next release and/or the contributing guide if placing this responsibility on the first PR merged post a release (this feels a little dangerous).

This is part of the default `usethis::use_release_issue()` checklist: https://github.com/r-lib/usethis/blob/467ff57f92afb34878dc411c46e3f0de029ceea4/R/release.R#L142
