### ISSUE TITLE
rstan exposing functions is failing in CI

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#307]
As above this is a new issue and is causing all checks to fail. Everything works locally so the precise issue is unclear. I have hotfixed by removing skipping this test on all CI but obviously this isn't a sensible long-term solution. 

See https://github.com/epinowcast/epinowcast/actions/runs/5823160125/job/15789401806

**Comment by medewitt** [comment]
Just sticking this here...CmdStanR now has this functionality (https://mc-stan.org/cmdstanr/reference/model-method-expose_functions.html). Syntax  for handling outputs is slightly different with list environments. I hate rstan deps...

**Comment by seabbs** [comment]
yup we are using that now (sorry should have been clearer when closing)

**Comment by medewitt** [comment]
> yup we are using that now (sorry should have been clearer when closing)

Doh, sorry-- That's what I get when I read things on my phone...

**Comment by seabbs** [comment]
haha no worries!
