### ISSUE TITLE
enw_filter_delay function: Filter based on report - reference date

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#344]
**Is your feature request related to a problem? Please describe.**
When using `epinowcast` it is often useful to compare nowcasts against later observed data. When doing this there are two sensible choices. The first is supported and is to filter the latest data at some future point and then use `enw_latest_data()`.  The second is to filter the data a consistent delay after the reference date so that all reference dates have the same horizon. This is currently unsupported. 

**Describe the solution you'd like**
A new function called `enw_filter_delay` or similar that is based on the current `enw_filter_reference` and `enw_filter_report` functions and enables users to filter out reported data greater than some maximum delay. 

The new function should be clearly documented and have an example workflow. It should also have an informative news item that lays out why a user might want to use it.

**Comment by seabbs** [comment]
Fool that I am I missed that this function exists in the form of `?enw_delay_filter`. I think we should like rename to the suggestion here though to make it inline with the rest of the filter functions.

**Comment by kathsherratt** [comment]
I'm up for this - will put in a PR (should be early next week).
