### ISSUE TITLE
Set up system to sync `CITATION` and `DESCRIPTION` as well as `citation.cff`.

### ISSUE THREAD

**Issue by jamesmbaazam** [epinowcast/epinowcast#367]
It would be good to implement the citation syncing system in {EpiNow2} implemented in https://github.com/epiforecasts/EpiNow2/pull/467. 

This would involve:

* regenerating CITATION when relevant fields in DESCRIPTION change,
* generating a `citation.cff` file through a workflow that tracks both CITATION and DESCRIPTION.

I'm happy to submit a PR if you think it's worth implementing here.

**Comment by seabbs** [comment]
Yes I agree that would be great! Thanks @jamesmbaazam looking forward to the PR.
