### ISSUE TITLE
Move generic community elements (e.g. Code of Conduct) to organizational level

### ISSUE THREAD

**Issue by pearsonca** [epinowcast/epinowcast#371]
Per [github community notes](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file), some of the community-related automagic files can be auto-magic-ed from the [organizational level](https://github.com/epinowcast/.github).

Propose making this move for Code of Conduct + Contributing guidelines.

Pro: one location, less non-code in packages. Con: have to do it, less (organizationally) portable maybe?

**Comment by pearsonca** [comment]
Related: there's a bit of other top-level non-code that might also be better to live in this packages `.github` folder (e.g. Style Guide), again to induce a cleaner/more organized top-level package directory.

**Comment by seabbs** [comment]
Sounds like a great idea @pearsonca. Not sure about the style guide as might be a bit confusing for non-GitHub users? Do we have any good examples of where people usually put these?

**Comment by seabbs** [comment]
It sounds like `docs` is the right call for things that organise development. I feel like we could also do with some boilerplate for these other files that can be improved over time? 

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by pearsonca** [comment]
I don't have write auth against the organizational repo, so need to fix that - otherwise prepped a branch there adding the docs, and will make some changes against epinowcast/not-epinowcast to feel out how precisely inheritance, linking, etc works.
