### ISSUE TITLE
minimum supported R version 3.5 or 4.1

### ISSUE THREAD

**Issue by medewitt** [epinowcast/epinowcast#389]
**Describe the bug**

Current source code (e.g.,  [here](https://github.com/epinowcast/epinowcast/blob/b996732ccc4d5fc980715aff3d116d68fe52158c/R/model-modules.R#L452)) uses some of the new syntax (`|>` in the vignettes, `\(x, y)` lambda functions) in R not available until 4.1.0. Currently, the minimum version supported in the package description is 3.5.

**To Reproduce**
See source code.

**Expected behavior**
Ideally source and DESCRIPTION are consistent. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
N/A

**Additional context**
I just wanted to bring attention to this. Maybe everyone has upgraded to R >= 4.1.0 and this isn't an issue (and we bump the R version in the DESCRIPTION). 

Some old academic servers and clusters might still be running R 3.6.x (this was case with CentOS server I previously ran), so could choke on the new requirements. Either way I think DESCRIPTION and the functions used need to be consistent.

**Comment by pearsonca** [comment]
I think the idea is that's "legal" syntax in the vignettes (which people can run elsewhere, or downgrade manually), while the package only actually *requires* the specified version to run.

**Comment by seabbs** [comment]
Thanks for flagging @medewitt -  this is a good point. 

I think from a technical sense what @pearsonca is saying is definitely true but also think we want to be presenting as consistent an experience as possible. 

Personally, I would be very happy increasing the dependency to `4.1.0` - especially given that we are so dependent on `cmdstanr` and `cmdstan` and that versioning for those is currently difficult. On the other hand if we stuck with the technical dependency declaration then maybe we should update some documentation to indicate this to users (and maybe flag vignettes with a warning?).

**Comment by medewitt** [comment]
Makes sense @pearsonca . It looks like the only non-vignette use is in `enw_expectation`  with new lambda function syntax. That could revert the the old-style `function( x, y)` syntax and R3.5 minimum wouldn't fail unless someone trying to build the vignettes (i.e., install.packages( build_vignettes = TRUE)` or build from source.

It might just be a nitpick and really a non-issue?

**Comment by pearsonca** [comment]
If the >3.5 syntax is used outside vignettes (or other build/test infrastructure, etc), including documentation examples, *that is an issue*.

In the vignette, I'm less fussed about it - indeed, I prefer the 4+ syntax there: its just better and we should normalize/encourage its use. I suppose we might footnote some caveats about using the 4+ syntax in the vignettes.
