### ISSUE TITLE
Consider removing author names from vignettes

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#415]
**Is your feature request related to a problem? Please describe.**
Currently, vignettes have a list of authors at the top. These can easily become out of date due to PRs on those vignettes that miss adding in new authors. Additionally, clearly showing individual level authorship like this seems to be a bit of a signal in the wrong direction in terms of the community vibe we are going for. 

**Describe the solution you'd like**
Entirely remove the authorship field + (ty @sbfnk) add in a link to the source file for each vignette as that will naturally track contributions.

**Describe alternatives you've considered**
Use a team authorship.

**Additional context**
This needs input from current vignette authors: @adrian-lison @sbfnk @FelixGuenther @zsusswein @pearsonca @medewitt @jamesmbaazam.

**Comment by seabbs** [comment]
> ot just vibe - these efforts genuinely reflect what's in the "air" discussion wise, what other people have done in terms of syntax choices, documentation

Vibe is the "air" that wasn't meant in a negative sense.

> edit: also, am I a vignette author? Pretty sure I embraced the "team authorship" approach for the quickstart.

You are on the getting started with stan vignette. 

>  having a drafter or some such acknowledgement

Yes we could do this. There is a question more broadly then though as we would also need to decide what to do about code. I would favour keeping things simple and keeping contributions centralised (though keen to think about better ways to show those that the current DESCRIPTION authorship and news file log).

**Comment by sbfnk** [comment]
I agree with removing authorship. One thing to retain some level of attributing credit would be to link directly to the source file from the rendered vignette which people could then peruse for the full contribution history.

**Comment by pearsonca** [comment]
> I agree with removing authorship. One thing to retain some level of attributing credit would be to link directly to the source file from the rendered vignette which people could then peruse for the full contribution history.

Nicely practical way to give all the infos; introduces a bit of overhead to ensure links are present, but even that seems potentially automate-able, especially given the pre-rendering process for vignettes.

**Comment by seabbs** [comment]
Yes, I agree that linking to the source file seems like a really nice way to solve this.

**Comment by adrian-lison** [comment]
Fully agree with the above, happy to have authorship removed

**Comment by athowes** [comment]
At the moment I am writing vignettes and contibuting to the code base for existing Epinowcast community projects as part of my work with the CDC CFA. Within this remit, I would prefer that my contributions are acknowledged via authorship of the vignettes. As to whether this is optimal for your community or not, I don't know, and I agree there are arguments on either side. I will say that I am disincentivied from contributing by not having names on vignettes, though whether that's enough to change my behaviour much I don't know.

I think one thing that is relatively unique / strange about my situation is that I can imagine putting months of work into Epinowcast community vignettes (or more, we will see). So I think particularly in this situation it does feel bad. As I say, I may still want to do this, but ideally I would retain some kind of possibility of doing academic work in the future (and I forsee it being possible I cut myself off from this).

> One way to retain some level of attributing credit would be to link directly to the source file from the rendered vignette which people could then peruse for the full contribution history.

This is technically true, but practically speaking I don't think is going to help with most things that people need credit for i.e. which hiring manager is looking through GitHub commit histories? (to be fair, perhaps it did help to get this job -- thanks @seabbs).

More broadly, I would be interested in ways for our "vignette" products to be citable. And as a result be viewed, read, criticised, more. So perhaps the solution doesn't have to be as narrowly defined as to whether there are names on vignettes or not.

**Comment by seabbs** [comment]
I think this is a really good discussion to have and we should open it up as much as possible. Given that I think we should move this to community.epinowcast.org. @athowes would you be able to make a post there with similar content to above and link back? 

Something I would say here is I would hope we construct the authorship of the packages themselves to be the think you would put in your CV etc and that would mean something.
