### ISSUE TITLE
Set up lintr in tests

### ISSUE THREAD

**Issue by Bisaloo** [epinowcast/epinowcast#417]
The `tests/` folder is currently excluded from the lintr checks:

https://github.com/epinowcast/epinowcast/blob/cb8434bf90e42c4739345c778bd53c45ef2ce217/.lintr#L12

We discussed in a PR I can't find now (:grimacing:) with @pearsonca how it would be beneficial to change that so opening this issue to track it.

**Comment by medewitt** [comment]
> We discussed in a PR I can't find now (:grimacing:) with @pearsonca how it would be beneficial to change that so opening this issue to track it.

https://github.com/epinowcast/epinowcast/pull/402#issuecomment-1826756326 😄
