### ISSUE TITLE
Render custom stan functions using Doxygen

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#423]
**Is your feature request related to a problem? Please describe.**
The current stan documentation (added in #422) follows the suggested format in the stan docs which themselves are based on Doxygen. However, this documentation is not currently rendered so is hard to navigate and in some cases read.

**Describe the solution you'd like**
Using Doxygen to render our documentation similarly to done [here](https://github.com/spinkney/helpful_stan_functions/tree/main). Note there is no official stan support and this example is the only one I have seen. Once this is in place we would also need to clearly link from the main package site.

**Describe alternatives you've considered**
A different documentation system but it is not clear to me what this would be.

@sbfnk @jamesmbaazam might be interested in this for `EpiNow2`.

**Comment by seabbs** [comment]
I looked at this again and it really looks like it is just a case of telling Doxgyen that the stan file is a c++ file (in the Doxyfile) and then using the documentation approach they have taken in their stan functions (which has some slight differences to what we have so far). Given this I think this should be higher priority and have moved it up a version. 

If anyone wants to take this on that would be great but if not I am happy to.

**Comment by jamesmbaazam** [comment]
I'm taking a stab at this in preparation for the linked issue in EpiNow2. @seabbs What is desired output format? Options include PDF, HTML, etc. Who do we want to expose this to? I would imagine it's more of a developer doc?

**Comment by seabbs** [comment]
I think we want to output it to a website very much like the linked `helpful_stan_functions` example. 

That would be great!
