### ISSUE TITLE
Support for missing reference dates MVP

### ISSUE THREAD

**Issue by adrian-lison** [epinowcast/epinowcast#43]
### Design motivation
Some datasets may include counts of cases with missing reference dates. For these cases, the date of reporting is known but the date of occurrence is for some reason unknown. It would be a valuable feature to support such data.

One way to account for such "missing data" in nowcasting is imputation during preprocessing. This is typically done by estimating the delay distribution from historical data and imputing reference dates by subtracting random draws of the delay distribution from the reporting date. Regression models can be used to estimate the delay distribution, accounting for changes over time, on weekdays, group effects etc. This however means that two potentially sophisticated models are involved (the imputation model and nowcasting model), and to quantify the overall uncertainty, a multiple imputation scheme is required which can be computationally demanding if the nowcasting model must be rerun. More importantly however, subtracting delays from reporting days does not necessarily reconstruct the underlying time series by reference date. This is the same issue as with back-projection approaches used in R estimation (see https://doi.org/10.1371/journal.pcbi.1008409).

It thus seems more favorable to support missing reference dates directly in the nowcasting model by implementing a generative model of missingness and adding a likelihood term for the cases with missing reference date. In the following, an MVP version for `epinowcast` of such a model is outlined.

### Changes to the interface (preprocessing)
1. Implement an artificial/simulated dataset with cases with missing reference dates (`NA`) for testing and showcasing purposes. Ideally, also add a real-world dataset with cases with missing reference dates.
2. Adjust `enw_preprocess_data` to accept entries where the `reference date` is `NA` and gather them into a vector `obs_miss` that is indexed by reporting day. Add `obs_miss` to the returned `enw_preprocess_data` object.
3. Adjust `enw_obs_as_data_list` such that the `obs_miss` in `pobs` are also returned in the data list for stan.

### Changes to the model
1. Add `int obs_miss[rd]` to the data block. This array will contain the number of cases with missing reference date reported on a certain reporting date.
2. Add `vector<lower=0,upper=1>[t] alpha[g]` to the transformed parameters block. This will represent the share of cases with (eventually) recorded reference date information that occurred on a given reference date for a given group. In turn, `1-alpha` will represent the share of cases with (eventually) missing reference date information.
3. Implement a per-group, non-centered random walk prior on the logit scale for `alpha`. This will require corresponding parameters for the raw random walk. Also, add `real eobs_miss_lsd_p[2]` as priors for the random walk sd to the data block. The random walk will be similar to https://github.com/epiforecasts/epinowcast/blob/20274a8bb7effcae76d35cbcfd3eba5186d34dc3/inst/stan/epinowcast.stan#L106-L116
4. Remove the currently implemented map-reduce structure from the likelihood. The `exp_obs` from all reference dates (for a given group) are needed to compute the expectation for `obs_miss` by convolving over all `maxDelay` days before a reporting date. Hence it make sense first implement a working version without within-chain parallelization and then add it back at a later stage.
5. Add a multiplication of `exp_obs` with the corresponding `alpha` to get the expected numbers of cases with (eventually) _recorded_ reference date information for the different delays, before putting it in the likelihood for `obs`: https://github.com/epiforecasts/epinowcast/blob/20274a8bb7effcae76d35cbcfd3eba5186d34dc3/inst/stan/functions/obs_lpmf.stan#L17
6. Add a multiplication of `exp_obs` with the corresponding `1-alpha` to get the expected numbers of cases with (eventually) _missing_ reference date information for the different delays. Then add them to a vector `exp_obs_miss` that is indexed by reporting day (matching the reporting day with the right delay from the current reference date). Looping over the different reference dates (`exp_obs_miss` initialization is outside of the loop), this will realize the convolution.
7. Implement a second likelihood term (poisson or neg_binomial) for `obs_miss` given `exp_obs_miss` as expectation. **IMPORTANT:** only include the likelihood for `obs_miss` at `t_0 + maxDelay` or later! Earlier `obs_miss` are not supported in the MVP version since this would require an extension of the model to times before `t_0`.
8. If a neg_binomial likelihood is used and an independent overdispersion for the missing data is desired, add a `phi_miss` parameter with suitable prior (having partially pooled overdispersion parameters would probably be overengineered).
9. Adjust `generated quantities` in a similar way to the likelihood computation such that `pp_obs_tmp` only represents the cases with known reference date and add a `pp_obs_miss_tmp` for the cases with missing reference date. Analogously, distinguish between `pp_inf_obs` and `pp_inf_obs_miss`. Adjust the log-likelihood computation such that both likelihoods are taken into account. 

### Changes to the interface (postprocessing)
1. Adjust plotting and summary functions such that the different generated quantities for known and missing cases are handled separately.
2. Optionally add support for plotting the estimated shares of known/missing cases.
3. Ensure that only the observations and predictions for the cases with known reference date are used in the evaluation procedures.

### Further remarks
1. The generative model suggested here comes with the standard "missing-at-random" assumption, i.e. the reporting delay is assumed to be independent of the missingness.
2. Splitting up the likelihood into cases with known and with missing reference date is only theoretically justified if we assume that reported cases are Poisson distributed (since the sum of Poisson distributed RVs is also Poisson). Switching this to negative binomial means some slight inaccuracies in that regard. However this does not mean that using a negative binomial cannot offer improved performance on real-world data. It is only less principled.
3. As noted above, this MVP only supports `obs_miss` at `t_0 + maxDelay` or later. Nevertheless, I suggest to write the whole interface as if also earlier observations could be included, because we can then extend the model later on without touching the interface again. This only means that the details of the likelihood should be clearly communicated to the user.

**Comment by seabbs** [comment]
This is very thorough and looks like it should work well. I think you have essentially covered all the steps and I agree that handling missing observations as an additional vector in pre and post-processing is going to be 1. easiest to implement and 2. most robust. 

My own large scale suggestion would be to implement the optional switches for this model (so the user can specify the imputation of missing data on/off + it definitely does happen when there is no missingness). This should be fairly easy with the insertion of [miss ? lengh : 0] to all the parameter declarations and an if/else for the alpha scaling. It is not that elegant but aside from regex out the code is I think the only option. 

## Detailed comments

> Add int obs_miss[rd] to the data block. This array will contain the number of cases with missing reference date reported on a certain reporting date.

This will likely need some kind of group and time look-up alongside it. 

> Splitting up the likelihood into cases with known and with missing reference date is only theoretically justified if we assume that reported cases are Poisson distributed (since the sum of Poisson distributed RVs is also Poisson). Switching this to negative binomial means some slight inaccuracies in that regard. However this does not mean that using a negative binomial cannot offer improved performance on real-world data. It is only less principled.

I was wondering about this. At the moment there is no support for other likelihoods. I had considered adding Poisson support but had elected not to with the assumption that a large prior for overdispersion could be used if desired by the user and that in nearly all real-world implementations it is likely overdispersion will be present. 

I was also wondering if there was any case for other likelihoods like beta-binomial and its higher-order relatives. Just a random thought though. 

> If a neg_binomial likelihood is used and an independent overdispersion for the missing data is desired, add a phi_miss parameter with suitable prior (having partially pooled overdispersion parameters would probably be overengineered).

Obviously, lots of options here. I think your suggestion is a good one for the MVP. Making it be shared between missing and non-missing or partially pooled etc all possible future expansions.

**Comment by adrian-lison** [comment]
Thanks for your feedback on the feature issue!

I like your suggestion of splitting the project up into three PRs. I feel confident to work on the model and preprocessing PR first, but for the postprocessing and visualisation, a common discussion and maybe shared dev would make sense I guess.

Good suggestion to make this optional in the model via the inline ifelse trick, let's do it.

Regarding #40, I feel like it does not really make a big difference for the complexity of adding the feature.

I also think that offering the negative binomial as a default distribution makes a lot of sense. I am not sure if we can get any further by thinking about which distribution reflects which aspects of the underlying data-generating process - or whether this really helps in practice as we are far away from the abstract model anyways. So we might as well judge the different models simply by their real-world performance.

**Comment by seabbs** [comment]
> I like your suggestion of splitting the project up into three PRs. I feel confident to work on the model and preprocessing PR first, but for the postprocessing and visualisation, a common discussion and maybe shared dev would make sense I guess.

Sounds like a good plan. 


>  I am not sure if we can get any further by thinking about which distribution reflects which aspects of the underlying data-generating process - or whether this really helps in practice as we are far away from the abstract model anyways. So we might as well judge the different models simply by their real-world performance.

Agree. I think at some point supporting some options would be nice but doesn't seem like it needs to happen now.

**Comment by seabbs** [comment]
See work in progress on this in #64

**Comment by seabbs** [comment]
Data could be added from @FelixGuenther as an example dataset with missingness. At a later date recreating that analysis with the joint model could be a really nice case study.
