### ISSUE TITLE
Review test warnings and messages

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#434]
It looks like #417 may have accidently reintroduced an issue we saw where snapshot tests were not being correctly recognised by testthat. We also see a few messages during testing (like `scoringutils` being loaded that we should silence if we can.

**Comment by seabbs** [comment]
This shows up as a warning for a new snapshot for snapshots that have a testthat message with a linebreak. Solution for now is to remove those line breaks (and use nolint) and then check the status of all snapshots. I think as part of this we should also look at making warnings cause errors in our CI so that we can more easily detect this in the future.

**Comment by Bisaloo** [comment]
My apologies for breaking this :disappointed:. I see you already self-assigned but let me know if I should deal with it myself since I'm the one who caused it.

For a potential long-term solution, I see there is already a report for this in testthat bug tracker: https://github.com/r-lib/testthat/issues/1900.

https://github.com/epinowcast/epinowcast/pull/343 should help with the second part but has been stuck for a little while. Let's continue the discussion there on how to move forward.

**Comment by seabbs** [comment]
Oh no it's my bad. I knew this was a problem but completely lost track of it and forgot to document it. I'm happy to do the temporary fixing as described (unless you can think of a better solution?).

Do you have a suggestion for recording that this needs to be fixed once https://github.com/r-lib/testthat/issues/1900 is resolved? Perhaps just opening an issue describing what needs to be done and what the blocker is?

**Comment by seabbs** [comment]
> https://github.com/epinowcast/epinowcast/pull/343 should help with the second part but has been stuck for a little while. Let's continue the discussion there on how to move forward.

Also yes definitely and I am happy with the proposed solution. 

FYI having this in place was really helpful for #407 as that needed to not change the environment variables outside of the tests.

**Comment by Bisaloo** [comment]
> I'm happy to do the temporary fixing as described (unless you can think of a better solution?).

No better solution, this sounds like the most sensible option.

> Perhaps just opening an issue describing what needs to be done and what the blocker is?

Yes, this sounds good. Although the multiline description felt a bit strange anyways so maybe keeping the `# nolint` comments there is also an acceptable solution long-term :shrug:.
