### ISSUE TITLE
Checks are failing due to the ggplot2 update breaking snapshots

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#443]
Checks are failing due to the ggplot2 update breaking snapshots

_Originally posted by @seabbs in https://github.com/epinowcast/epinowcast/issues/442#issuecomment-1968974568_

**Comment by pearsonca** [comment]
What is the operational intent with snapshots? Specifically, does it make sense to be snapshotting graphics output or is that too much?

My impression is the intent is in the direction of integration testing - being able to verify more complex behavior in the orchestration of multiple bits by comparison to a more complicated object. Generating plots falls into that category (though I have to flog my regular point on whether plotting belongs in this library or not), but perhaps there's a way to check that the plots can be generated without having to get a pixel/byte match.

**Comment by seabbs** [comment]
Yes and it makes it easier to get a robust test coverage in the absence of enough resource to do more work on the test suite. They aren't stable enough for production code but are useful in dev as long as aware of how fragile they can be and promptly fix issues like above. In a perfect world we would have no code snapshot tests (there are still a fair few) and likely fewer image snapshots.
