### ISSUE TITLE
automated workflows that commit don't trigger checks

### ISSUE THREAD

**Issue by sbfnk** [epinowcast/epinowcast#447]
In https://github.com/epinowcast/epinowcast/pull/446 the final commit is an automated commit with `[ci skip]` - but if I understand correctly this means merge conditions (5 required checks pass) are never met. Should we avoid using `[ci skip]` in commits from workflows?

**Comment by Bisaloo** [comment]
As discussed in https://github.com/epiforecasts/scoringutils/issues/601, `[ci skip]` is a red herring here and has no functional impact. Commits made by `secrets.GITHUB_TOKEN` will not trigger workflows.

**Comment by sbfnk** [comment]
Thanks, now I remember! So just triggering these on `main` seems indeed the only viable solution.

**Comment by sbfnk** [comment]
Given that this is continuing to be a pain (and the `main` triggering didn't solve things as pushing directly there violates branch protection rules) why don't we use an (organisational-level) PAT instead of the github token?

**Comment by seabbs** [comment]
To get overcome branch protection rules?

**Comment by sbfnk** [comment]
What I meant is: if the fundamental issue is that

> Commits made by `secrets.GITHUB_TOKEN` will not trigger workflows.

why don't we make these commits using a PAT instead, such that workflows to get triggered? Then we could go back to the original plan of updating the README inside PRs (within branch protection rules).

**Comment by seabbs** [comment]
> why don't we make these commits using a PAT instead, such that workflows to get triggered? Then we could go back to the original plan of updating the README inside PRs (within branch protection rules).

Isn't the issue that they don't trigger workflows but the PR expects the workflows to be triggered and so you get stuck unable to merge due to waiting on your required workflows?

**Comment by sbfnk** [comment]
Yes but (if I understand the whole discussion correctly) if we used our own PAT (which would add risk and would have to be appropriately restricted) then actions would be triggered.
That said it failed when trying in
https://github.com/epiforecasts/EpiNow2/pull/609
though it does seem to work in
https://github.com/european-modelling-hubs/covid19-forecast-hub-europe-submissions/blob/32b583511181630c7bd53d8304a613b1220a70d0/.github/workflows/automate_baseline.yml#L44

**Comment by seabbs** [comment]
ah right got you.

**Comment by sbfnk** [comment]
I think this has been closed by #450?
