### ISSUE TITLE
Pkgdown enwtheme not being used 

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#452]
As the title currently the custom `epinowcast/enwtheme` is not being used. Looking at the output of `pkgdown` this failure is silent.

There has been a recent `pkgdown` update which may have led to this behaviour. @Bisaloo pinging in case you know what this is?

**Comment by Bisaloo** [comment]
It is used as far as I can tell. What makes you say it's not used?

**Comment by seabbs** [comment]
When it was building the dev docs it used the right theme (i.e the one being specified in the enwtheme) and now it's using the default theme? Your right in the sense the sidebar changes are showing up etc.

**Comment by seabbs** [comment]
I.e package.epinowcast.org Vs package.epinowcast.org/dev

**Comment by Bisaloo** [comment]
We have issues with the pkgdown update in other packages as well. This seems to be the fix: https://github.com/epiverse-trace/epiCo/pull/119/files.

I can't test it locally right now so feel free to give it a go or I will try again later next week.

**Comment by Bisaloo** [comment]
This will be fixed by https://github.com/r-lib/pkgdown/pull/2441 as soon as it hits `main` since we're installing pkgdown from its GitHub repo.

**Comment by Bisaloo** [comment]
This is now fixed: https://package.epinowcast.org

**Comment by pearsonca** [comment]
If we've bumped pkgdown version, then #381 should also be fixed now?
