### ISSUE TITLE
Add/Check support for using a `Cmdstan` fit as initial conditions for a new fit + support passing from pathfinder to NUTS

### ISSUE THREAD

**Issue by seabbs** [epinowcast/epinowcast#465]
As the title says with the latest version of `cmdstanr` (https://github.com/stan-dev/cmdstanr/releases/tag/v0.8.0) there is now support for using a fit `cmdstan` object to initialise a new fit. 

This would likely be of use to users and so should be exposed (checking/testing that an object of this kind can be passed seems sensible. 

We can also now easily initialise NUTS using pathfinder and it seems like this is related enough to be part of this issue. To do this I am currently thinking we would add a new function `enw_initialise_with_pathfinder` that takes another sampling function as an arg (i.e it calls pathfinder and then uses that call as an init for the specified function` or an argument to `enw_sample`. Not clear what the best choice is?

This issue is related to #464 but does not depend on it

**Comment by jamesmbaazam** [comment]
There is now some more information provided in the docs: https://github.com/stan-dev/docs/pull/833/files?show-viewed-files=true&file-filters%5B%5D=.
