### ISSUE TITLE
Add support for aggregation of probabilities in `expected_obs`

### ISSUE THREAD

**Issue by jessalynnsebastian** [epinowcast/epinowcast#481]
Toward using delay probability aggregation to encode a fixed reporting cycle into `epinowcast`, the Stan function `expected_obs` will need to be modified to take in an argument specifying which dates to be aggregated and which dates they should be aggregated to. This will likely be a square matrix with dimension `max_delay` which, when right-multiplied to the delay probability vector, will output new delay probabilities aggregated to the appropriate reporting days.

**Comment by seabbs** [comment]
Agree this sounds like a good step towards aggregation of probabilities. It would be good to be able to track this in a larger meta issue if possible (i.e for the entire feature).
