### ISSUE TITLE
Extend to arbitrary time frames for input data

### ISSUE THREAD

**Issue by sbfnk** [epinowcast/epinowcast#81]
The package works on daily data, and daily data only. While most use cases that I can think of will indeed involve daily data, this is not necessarily the case universally, and it limits the scope of what the package can do if there is no way for time steps do be anything shorter (e.g. hour) or longer (e.g. month) than a day.

In order to be open to other options here in the future I would suggest to design the workflow such that all dates are converted to integer time steps at the preprocessing stage, and all steps following preprocessing use these integer times only - this would keep the code more modular and mean that if someone wants to implement other options later this only has to be changed in preprocessing (which in my opinion could be in a separate package anyway - but that is a separate discussion).

**Comment by seabbs** [comment]
I think the majority of code (excluding post-processing) is functional without depending on daily data. There are a few instances which @adrian-lison has identified where this is not the case. Agree it is good to work across scales.


Yes, it could be, as could the formula interface. I am happy to talk about dev models and whether others take on these parts of the code base and deliver specified objects for downstream usage. I don't think stretching across multiple packages is a good idea for this project, at this stage, given resource levels.

**Comment by seabbs** [comment]
An approach for dealing with this could be declaring a timespan in `enw_preprocess_data` and `enw_complete_dates` and then updating the preprocessing to know about this. This approach would give any date-based post-processing and model steps for free I think. 

Potentially, would also need another function to help the user aggregate the data properly for there chosen timespan but equally there is an argument that this could be left as an excercise for the reader.
